name: Python Syntax Checker

on:
  pull_request:
    branches:
      - main

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install opencv-python
        pip install tensorflow
        pip install matplotlib

    - name: Check Python syntax
      run: |
        flake8 DL_MODEL/person1.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 DL_MODEL/person1.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
